version: "3"
# docker run --rm --name WebImage -p 82:8080 webimage
# When run with docker-compose: rm unneccessary because modifier is run by "docker-compose down"

services:
  webimage:
    container_name: WebImage
    image: webimage:latest
    ports:
      - 82:8080
    environment: 
      - WIDTH=32
      - HEIGHT=32
    cap_add:
      - NET_ADMIN
      - Net_BIND_SERVICE
    restart: unless-stopped
